[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "blueglass"
version = "0.1.0"
description = "Blue Glass deep learning environment"
requires-python = ">=3.11"

dependencies = [
]
